### ISSUE TITLE
Running the package creates 100+ GB of data

### ISSUE THREAD

**Issue by amlobat2** [ldesousa/r.mblend#15]
Hello, I am knew to the world of GIS and have been experimenting with blending rasters. When I try to run the mblend module in GRASS, it runs almost all the way through, then I get this error:

`WARNING: Unable to write 552513 bytes: No space left on device  
ERROR: Error writing compressed FP data for row 0 of <tmp_456409>: No such file or directory  
Region:  
{'projection': 1, 'zone': 16, 'n': 4540856.77379945, 's': 4428064.48102117, 'w': 329140.06822132, 'e': 416029.15304229, 'nsres':  
 1.0000026, 'ewres': 1.00000098, 'rows': 112792, 'cols': 86889, 'cells': 9800384088}  
WARNING: No data base element files found  
WARNING: No data base element files found  
WARNING: No data base element files found  
WARNING: No data base element files found  
WARNING: No data base element files found  
WARNING: No data base element files found  
WARNING: No data base element files found  
WARNING: No data base element files found  
WARNING: Unable to drop table: 'drop table tmp_456408'  
WARNING: Unable to delete table <tmp_456408>  
Traceback (most recent call last):  
  File "C:\Users\12248\AppData\Roaming\GRASS7\addons/scripts  
/r.mblend.py", line 282, in <module>  
    main()  
  File "C:\Users\12248\AppData\Roaming\GRASS7\addons/scripts  
/r.mblend.py", line 207, in main  
    gscript.run_command('r.grow.distance', input=high,  
distance=dist_high)  
  File "C:\Program Files\GRASS GIS  
7.8\etc\python\grass\script\core.py", line 441, in  
run_command  
    return handle_errors(returncode, returncode, args,  
kwargs)  
  File "C:\Program Files\GRASS GIS  
7.8\etc\python\grass\script\core.py", line 343, in  
handle_errors  
    returncode=returncode)  
grass.exceptions.CalledModuleError: Module run None  
r.grow.distance input=USGS_one_meter_x39y445_IL_12_County_Ch  
ampaignCo_2008@PERMANENT distance=tmp_456409 ended with  
error  
Process ended with non-zero return code 1. See errors in the  
(error) output.`  

I had over 150 GB of space left on my computer before running the module. Does running it really take up that much space or am I doing something wrong? Are there any settings I could change to decrease the amount of data that is created? Any help would be appreciated!

**Comment by ldesousa** [comment]
The module creates various intermediate rasters, but they should not take that much space. How large are the inputs you are feeding to the module?

**Comment by amlobat2** [comment]
One is about 50,000 KB and the other is close to 500,000 KB.

**Comment by amlobat2** [comment]
I am still struggling with this issue and would appreciate any advice/help!

**Comment by ldesousa** [comment]
I still can not replicate this issue. Grids of 50 KB and 500 KB are really small, they should not create this kind of problem. Can you get those grids to me somehow?

**Comment by amlobat2** [comment]
By reinstalling GRASS, I was able to solve this issue.
