### ISSUE TITLE
r.mblend error "grass.exceptions.CalledModuleError: Module run None v.surf.idw input=tmp_3289117 column=value output=tmp_3289118 power=2 npoints=50 ended with error"

### ISSUE THREAD

**Issue by amlobat2** [ldesousa/r.mblend#17]
Hello, I am trying to use r.mblend for the first time and I am struggling with the following error:

`[r.mblend] Interpolating smoothing surface. This might take a while...  
Traceback (most recent call last):  
  File "/Users/michaelalobato/Library/GRASS/7.8/Modules/scripts/r.mblend", line 282, in <module>. 
    main()
  File "/Users/michaelalobato/Library/GRASS/7.8/Modules/scripts/r.mblend", line 257, in main   
    gscript.run_command('v.surf.idw', input=points_edges, column=COL_VALUE,   
  File "/Applications/GRASS-7.8.app/Contents/Resources/etc/python/grass/script/core.py", line 441, in run_command   
    return handle_errors(returncode, returncode, args, kwargs)   
  File "/Applications/GRASS-7.8.app/Contents/Resources/etc/python/grass/script/core.py", line 342, in handle_errors   
    raise CalledModuleError(module=None, code=code,   
grass.exceptions.CalledModuleError: Module run None v.surf.idw input=tmp_3289117 column=value output=tmp_3289118  
 power=2 npoints=50 ended with error  
Process ended with non-zero return code -9. See errors in the (error) output.   
WARNING: No data base element files found   
WARNING: No data base element files found   
WARNING: No data base element files found   
WARNING: No data base element files found   
WARNING: No data base element files found   
WARNING: Table <tmp_3289111> linked to vector map <tmp_3289111> does not   
         exist`

Does anyone have any suggestions as to how to fix this error? I am new to GIS softwares and not entirely sure where to start with this error.

**Comment by amlobat2** [comment]
Hello I am still running into this issue. Does anyone have any advice as how to overcome it?

**Comment by ldesousa** [comment]
The `v.surf.idw` module is failing because it can not find the attribute table of one the vector layers. This probably means something is going on with the GRASS bank-end database. Are you using the default SQLite back-end? Could you please post the output of the command `db.connect -p`?

**Comment by amlobat2** [comment]
I am using whatever is the default. When I ran `db.connect -p` I got `driver: sqlite
database: /Users/michaelalobato/Documents/Research/grassdata/champaign/PERMANENT/sqlite/sqlite.db
schema: 
group: `

**Comment by ldesousa** [comment]
Please check whether the table exists in the SQLite database. Start a session with:

`sqlite3 /Users/michaelalobato/Documents/Research/grassdata/champaign/PERMANENT/sqlite/sqlite.db`

Then list the existing tables:

`.tables`

If the table `tmp_3289111` exists, then list its description and post it here:

`.schema tmp_3289111`

**Comment by amlobat2** [comment]
When I run the `.tables` command, nothing is returned:

`sqlite> .tables`
`sqlite>`

I've done some googling in an attempt to solve the problem but I can't seem to solve the problem. Would an error like this be solved by uninstalling and reinstalling GRASS?

**Comment by ldesousa** [comment]
I am not sure this is an installation problem. If there are no tables it could be that the clean up routine is still running after the exception. Can you try to run `v.surf.idw` manually? You will need a points layer, but you can create something random.

**Comment by amlobat2** [comment]
I used this [sample dataset](http://www.kriging.com/datasets/coal.dat) to test the `v.surf.idw` module and I get this output:

`v.surf.idw input=coal_test@PERMANENT output=coal_test_tested`
`Input vector map <coal_test@PERMANENT> is 2D - using categories to interpolate`
`WARNING: No record for point (cat = 1)`
`WARNING: No record for point (cat = 2)`
`WARNING: No record for point (cat = 3)`
.
.
.
`WARNING: No record for point (cat = 96)`
`0 points loaded`
`ERROR: No points found`

**Comment by ldesousa** [comment]
Looks like something is indeed wrong with your GRASS installation. I have never seen this kind of error, GRASS appears unable to create vector layers properly. Could be some issue interacting with SQLite.

I suggest you refer this issue with `v.surf.idw` to the GRASS users list. If you do so please post here the link to the thread.

**Comment by amlobat2** [comment]
Thanks for your help! I posted the issue, the link is here https://lists.osgeo.org/pipermail/grass-user/2021-February/082209.html . I will be closing this issue now, but I am still having issues with `v.surf.idw`. If you are able to reach a solution, please visit the link and add a response.
