### ISSUE TITLE
How to run it?

### ISSUE THREAD

**Issue by iboates** [ldesousa/r.mblend#9]
Hello, I am just wondering how I can run this tool.  I have installed the grass module for my python installation but I still get `ImportError: No module named script` when I try to run it.

Thank you

**Comment by ldesousa** [comment]
The `script` module is packaged with GRASS, I suspect there is some issue with your installation. Could you please detail how did you install GRASS on your system?

**Comment by iboates** [comment]
Which version of Python is it written in? I get a syntax error when trying to run it with Python 3.5 so I am guessing 2.7?

After the `ImportError` I try using pip to install the GRASS bindings (I do have GRASS installed on my system), but it says that I have all requirements already satisfied:

```
isaac@ib:/media/isaac/Data/_GMCM/Slovakia_Website/python/r.mblend$ python2.7 r.mblend.py
Traceback (most recent call last):
  File "r.mblend.py", line 63, in <module>
    import grass.script as gscript
ImportError: No module named script
isaac@ib:/media/isaac/Data/_GMCM/Slovakia_Website/python/r.mblend$ pip2.7 install grass
Requirement already satisfied: grass in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: PyYAML in /usr/lib/python2.7/dist-packages (from grass)
Requirement already satisfied: coloredlogs in /usr/local/lib/python2.7/dist-packages (from grass)
Requirement already satisfied: click in /usr/local/lib/python2.7/dist-packages (from grass)
Requirement already satisfied: networkx in /usr/local/lib/python2.7/dist-packages (from grass)
Requirement already satisfied: numpy in /usr/lib/python2.7/dist-packages (from grass)
Requirement already satisfied: pandas in /usr/local/lib/python2.7/dist-packages (from grass)
Requirement already satisfied: tqdm in /usr/local/lib/python2.7/dist-packages (from grass)
Requirement already satisfied: rapclust in /usr/local/lib/python2.7/dist-packages (from grass)
Requirement already satisfied: statistics in /usr/local/lib/python2.7/dist-packages (from grass)
Requirement already satisfied: humanfriendly>=4.7 in /usr/local/lib/python2.7/dist-packages (from coloredlogs->grass)
Requirement already satisfied: decorator>=4.1.0 in /usr/local/lib/python2.7/dist-packages (from networkx->grass)
Requirement already satisfied: python-dateutil in /usr/lib/python2.7/dist-packages (from pandas->grass)
Requirement already satisfied: pytz>=2011k in /usr/lib/python2.7/dist-packages (from pandas->grass)
Requirement already satisfied: docutils>=0.3 in /usr/local/lib/python2.7/dist-packages (from statistics->grass)
Requirement already satisfied: monotonic; python_version == "2.6" or python_version == "2.7" or python_version == "3.0" or python_version == "3.1" or python_version == "3.2" in /usr/local/lib/python2.7/dist-packages (from humanfriendly>=4.7->coloredlogs->grass)
You are using pip version 9.0.1, however version 9.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

I am aware that I am not providing arguments, I just want to get it to execute properly once, even if they means failing due to lack of arguments before I start feeding inputs.

I am using Ubuntu 16.04

What is very strange though is that I can execute the command `import grass.script as gscript` in the GRASS python shell itself, it just fails when i try to do it from the terminal window.

**Comment by ldesousa** [comment]
@iboates two points to clarify:
 - PyGRASS and GRASS Script are not supposed to work with Python 3. Perhaps inconvenient but that is what we have.
 - You seem to be trying to run it "from source", instead of using the module - I imagine you wish to work on the code, good. However, like running the module, you need to run the code within a GRASS session, in order to have the environment all sorted out.

**Comment by iboates** [comment]
I see, I thought the instructions were intended for the command line. I figured out how to add custom extensions via SVN and did so, and now I can run the tool.  I am getting an error but i will raise another issue for that.
